### ISSUE TITLE
Is there a way to set a pruning ratio?

### ISSUE THREAD

**Issue by SvenMantowsky** [fxmeng/Pruning-Filter-in-Filter#17]
First of all, great work and great paper. 
I am writing a paper myself on the effect of pruning an robustness and it would be great if I could use your method along other a few others (especially because you are on the same or a higher level than the HRank method).

But in order to use the method, i need to be able to set some kind of pruning ratio to create a "fair" comparison and get a better insight. 
Is there a possibility to set some kind of "pruning ratio"?

Kind regards

**Comment by fxmeng** [comment]
Sorry for replying late,
In this method, we sparsify stripes during training, making it difficult to set the pruning ratio to a specific value accurately. You can set a target threshold for each layer to achieve your desired pruning ratio. Sparsify the stripes to this threshold and do not continue pruning beyond that point. Because SWP prunes stripes instead of filters, the resulting structure can still be significantly different from the predefined.
